import React, { useState } from 'react';
import { IndianRupee, Clock, MapPin, Plane, TrendingUp, Sparkles, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { predictPrice, getModelInfo, FLIGHT_OPTIONS } from '../api/client';

const shapFeatureLabel = (featureKey, formData) => {
    switch (featureKey) {
        case 'class': return `${formData.class} Class`;
        case 'days_left': return `${formData.days_left} Days Left`;
        case 'duration': return `Duration ${formData.duration} h`;
        case 'airline': return formData.airline.replace('_', ' ');
        case 'source_city': return `From ${formData.source_city}`;
        case 'destination_city': return `To ${formData.destination_city}`;
        case 'stops': return FLIGHT_OPTIONS.stops.find((s) => s.value === formData.stops)?.label || formData.stops;
        case 'departure_time': return `Departs ${formData.departure_time.replace('_', ' ')}`;
        case 'arrival_time': return `Arrives ${formData.arrival_time.replace('_', ' ')}`;
        default: return featureKey;
    }
};

const formatSigned = (value) => `${value >= 0 ? '+' : '-'}₹${Math.abs(value).toLocaleString('en-IN')}`;

const PricePrediction = ({ initialValues }) => {
    const [formData, setFormData] = useState({
        airline: 'Vistara',
        source_city: 'Delhi',
        destination_city: 'Mumbai',
        departure_time: 'Morning',
        arrival_time: 'Afternoon',
        stops: 'one',
        class: 'Economy',
        duration: 2.5,
        days_left: 10,
        ...initialValues,
    });

    const [prediction, setPrediction] = useState(null);
    const [modelInfo, setModelInfo] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: name === 'duration' || name === 'days_left' ? Number(value) : value,
        }));
    };

    const handlePredict = async (e) => {
        e.preventDefault();
        if (formData.source_city === formData.destination_city) {
            toast.error('Source and destination cities must be different');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const [predictionResult, info] = await Promise.all([predictPrice(formData), getModelInfo()]);
            setPrediction(predictionResult);
            setModelInfo(info);
            toast.success('Price prediction generated by the live model');
        } catch (err) {
            const message = err.response?.data?.detail?.[0]?.msg || err.response?.data?.detail || 'Could not reach the prediction API. Is the backend running on :8000?';
            setError(typeof message === 'string' ? message : 'Prediction request failed');
            toast.error('Prediction failed');
        } finally {
            setLoading(false);
        }
    };

    const topFeatures = modelInfo ? Object.entries(modelInfo.feature_importance).slice(0, 5) : [];

    const glassCard = 'bg-surface border border-border rounded-xl shadow-[0_2px_10px_-4px_rgba(0,0,0,0.1)] p-5';
    const cardHeader = 'flex justify-between items-center mb-4 pb-3 border-b border-border';
    const cardTitle = 'text-base font-semibold text-text-primary tracking-tight flex items-center gap-2';
    const glassLabel = 'flex items-center gap-1.5 text-xs font-medium text-text-secondary mb-1';
    const glassInput = 'w-full px-3 py-2 rounded-lg text-sm transition-all duration-200 bg-bg-secondary border border-border text-text-primary hover:border-text-tertiary focus:outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 cursor-pointer appearance-none';

    return (
        <div className="flex flex-col gap-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                
                {/* LEFT COLUMN: Grid Item wrapper for sticky child */}
                <div>
                    <div className="static lg:sticky lg:top-6 flex flex-col gap-6">
                        <div>
                            <h1 className="text-2xl font-bold text-text-primary mb-1 tracking-tight">Price Prediction</h1>
                            <p className="text-sm text-text-secondary">
                                Real XGBoost model trained on 300K+ Indian domestic flight fares.
                            </p>
                        </div>

                        <div className={glassCard}>
                            <div className={cardHeader}>
                                <h3 className={cardTitle}>Flight Details</h3>
                                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider bg-primary/10 text-primary border border-primary/20">
                                    <Sparkles size={12} />
                                    ML Powered
                                </span>
                            </div>

                            <form onSubmit={handlePredict} className="flex flex-col gap-4">
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <MapPin size={14} /> Source
                                        </label>
                                        <select name="source_city" value={formData.source_city} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.cities.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                                        </select>
                                    </div>
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <MapPin size={14} /> Destination
                                        </label>
                                        <select name="destination_city" value={formData.destination_city} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.cities.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                                        </select>
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Clock size={14} /> Departs
                                        </label>
                                        <select name="departure_time" value={formData.departure_time} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.timesOfDay.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                                        </select>
                                    </div>
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Clock size={14} /> Arrives
                                        </label>
                                        <select name="arrival_time" value={formData.arrival_time} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.timesOfDay.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                                        </select>
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Plane size={14} /> Stops
                                        </label>
                                        <select name="stops" value={formData.stops} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.stops.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}
                                        </select>
                                    </div>
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Sparkles size={14} /> Class
                                        </label>
                                        <select name="class" value={formData.class} onChange={handleInputChange} className={glassInput}>
                                            {FLIGHT_OPTIONS.classes.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                                        </select>
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Clock size={14} /> Duration (h)
                                        </label>
                                        <input type="number" name="duration" min="0.5" max="49.9" step="0.1" value={formData.duration} onChange={handleInputChange} className={glassInput} required />
                                    </div>
                                    <div className="form-group">
                                        <label className={glassLabel}>
                                            <Clock size={14} /> Days Left
                                        </label>
                                        <input type="number" name="days_left" min="1" max="49" value={formData.days_left} onChange={handleInputChange} className={glassInput} required />
                                    </div>
                                </div>

                                <div className="form-group">
                                    <label className={glassLabel}>
                                        <Plane size={14} /> Airline
                                    </label>
                                    <select name="airline" value={formData.airline} onChange={handleInputChange} className={glassInput}>
                                        {FLIGHT_OPTIONS.airlines.map((a) => <option key={a.value} value={a.value}>{a.label}</option>)}
                                    </select>
                                </div>

                                <button
                                    type="submit"
                                    className="inline-flex items-center justify-center gap-2 px-8 py-2.5 mt-2 rounded-lg text-sm font-semibold cursor-pointer transition-all duration-200 bg-primary text-white border-none shadow-md hover:bg-primary-hover hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:translate-y-0"
                                    disabled={loading}
                                >
                                    {loading ? (
                                        <>
                                            <div className="animate-spin">⏳</div>
                                            Predicting...
                                        </>
                                    ) : (
                                        <>
                                            <TrendingUp size={16} />
                                            Predict Price
                                        </>
                                    )}
                                </button>

                                {error && (
                                    <p className="text-danger mt-2 text-sm font-medium">
                                        {error}
                                    </p>
                                )}
                            </form>
                        </div>
                    </div>
                </div>

                {/* RIGHT COLUMN: Results */}
                <div className="flex flex-col gap-6">
                    {prediction ? (
                        <>
                            <div className="rounded-xl border border-primary/20 bg-primary/5 shadow-sm p-6 text-text-primary">
                                <div className="flex items-center gap-6 mb-6">
                                    <IndianRupee size={32} className="p-4 bg-primary/10 text-primary rounded-xl" />
                                    <div>
                                        <p className="text-sm text-text-secondary font-medium mb-1">Predicted Price</p>
                                        <h2 className="text-4xl font-extrabold text-primary tracking-tight leading-none">
                                            ₹{prediction.predicted_price.toLocaleString('en-IN')}
                                        </h2>
                                        <p className="text-sm text-text-tertiary font-medium mt-1">
                                            Model {prediction.model_version}
                                            {prediction.out_of_distribution && (
                                                <span className="inline-flex items-center gap-1 px-2 py-0.5 ml-2 rounded-md text-[10px] font-bold uppercase tracking-wider bg-warning/10 text-warning border border-warning/20">
                                                    <AlertTriangle size={12} /> Low confidence — unusual inputs
                                                </span>
                                            )}
                                        </p>
                                    </div>
                                </div>

                                <div className="flex items-center gap-4 p-4 bg-bg-secondary rounded-lg border border-border">
                                    <div className="flex flex-col items-center gap-1">
                                        <span className="text-xs text-text-secondary font-medium">Low</span>
                                        <span className="text-base font-bold text-text-primary">
                                            ₹{prediction.confidence_low.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                    <div className="flex-1 h-2 bg-border rounded-full relative overflow-hidden">
                                        <div className="absolute left-1/2 -translate-x-1/2 w-3 h-3 bg-primary rounded-full -top-0.5 shadow-sm"></div>
                                    </div>
                                    <div className="flex flex-col items-center gap-1">
                                        <span className="text-xs text-text-secondary font-medium">High</span>
                                        <span className="text-base font-bold text-text-primary">
                                            ₹{prediction.confidence_high.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {prediction.shap_contributions && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Why This Price (SHAP, this prediction only)</h3>
                                    </div>
                                    <pre className="m-0 p-4 bg-bg-secondary border border-border rounded-lg font-mono text-[13px] whitespace-pre-wrap overflow-x-auto text-text-secondary">
                                        <div className="flex justify-between gap-4 py-1">
                                            <span className="text-text-primary font-semibold">Base (Average) Price</span>
                                            <span className="text-text-primary font-semibold">₹{prediction.base_value.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
                                        </div>
                                        <div className="border-t border-dashed border-border my-1.5" />
                                        {prediction.shap_contributions.map((c) => (
                                            <div key={c.feature} className="flex justify-between gap-4 py-1">
                                                <span>{shapFeatureLabel(c.feature, formData)}</span>
                                                <span className={c.impact >= 0 ? 'text-danger' : 'text-success'}>
                                                    {formatSigned(c.impact)}
                                                </span>
                                            </div>
                                        ))}
                                        {prediction.other_features_impact !== 0 && (
                                            <div className="flex justify-between gap-4 py-1 italic text-text-tertiary">
                                                <span>Other Features</span>
                                                <span className={prediction.other_features_impact >= 0 ? 'text-danger' : 'text-success'}>
                                                    {formatSigned(prediction.other_features_impact)}
                                                </span>
                                            </div>
                                        )}
                                        <div className="border-t border-dashed border-border my-1.5" />
                                        <div className="flex justify-between gap-4 py-1 font-bold text-sm">
                                            <span className="text-text-primary">Final Prediction</span>
                                            <span className="text-text-primary">₹{prediction.predicted_price.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
                                        </div>
                                    </pre>
                                </div>
                            )}

                            {modelInfo && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Top Price Drivers Overall (training-time feature importance)</h3>
                                    </div>
                                    <div className="flex flex-col gap-3">
                                        {topFeatures.map(([name, score]) => (
                                            <div key={name} className="flex justify-between items-center p-3 bg-bg-secondary rounded-lg border border-border transition-colors hover:border-text-tertiary">
                                                <div className="flex items-center gap-4">
                                                    <span className="text-sm text-text-primary font-medium">{name}</span>
                                                </div>
                                                <span className="text-sm font-bold text-primary">{(score * 100).toFixed(1)}%</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {modelInfo && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Model Accuracy (held-out test set)</h3>
                                    </div>
                                    <ul className="list-none flex flex-col gap-3">
                                        <li className="flex items-start gap-2 p-3 bg-bg-secondary border-l-[3px] border-l-primary rounded-lg text-sm text-text-secondary">
                                            <Sparkles size={16} className="flex-shrink-0 text-primary mt-0.5" />
                                            <span className="font-medium text-text-primary">MAE:</span> ₹{modelInfo.metrics.mae.toFixed(0)} <span className="mx-1">|</span> <span className="font-medium text-text-primary">R²:</span> {modelInfo.metrics.r2.toFixed(3)}
                                        </li>
                                        <li className="flex items-start gap-2 p-3 bg-bg-secondary border-l-[3px] border-l-primary rounded-lg text-sm text-text-secondary">
                                            <Sparkles size={16} className="flex-shrink-0 text-primary mt-0.5" />
                                            <span className="font-medium text-text-primary">Trained on</span> {modelInfo.dataset}
                                        </li>
                                    </ul>
                                </div>
                            )}
                        </>
                    ) : (
                        <div className={`${glassCard} flex items-center justify-center text-center`} style={{ minHeight: 320 }}>
                            <div className="flex flex-col items-center gap-3">
                                <IndianRupee size={48} className="text-text-tertiary" />
                                <h3 className="text-lg font-semibold text-text-primary">No Prediction Yet</h3>
                                <p className="text-sm text-text-secondary font-medium max-w-[240px]">
                                    Fill in the flight details and click "Predict Price" to query the live model.
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default PricePrediction;
